# Generated by Django 6.0.2 on 2026-02-10 17:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fichero', models.CharField(max_length=255)),
                ('hash_sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('tamano_bytes', models.BigIntegerField(blank=True, null=True)),
                ('resultado_clase', models.CharField(max_length=50)),
                ('confianza_global', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('probabilidades_json', models.JSONField(help_text='Distribución de probabilidad de todas las clases')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Análisis',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFuncion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_memoria', models.CharField(max_length=50)),
                ('atencion_score', models.FloatField()),
                ('num_instrucciones', models.IntegerField(default=0)),
                ('entropia', models.FloatField(default=0.0)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_funciones', to='analisis.analisis')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Funciones',
                'ordering': ['-atencion_score'],
            },
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('UPLOAD', 'Subida de Binario'), ('DELETE', 'Borrado de Historial'), ('REPORT', 'Reporte de Falso Positivo')], max_length=20)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Logs de Actividad',
            },
        ),
        migrations.CreateModel(
            name='ReporteFalsoPositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_sugerida', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
                ('revisado_por_admin', models.BooleanField(default=False)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('analisis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analisis.analisis')),
            ],
        ),
    ]
