# Generated by Django 6.0.2 on 2026-02-12 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0004_detallefuncion_prediccion_especifica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisis',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='analisis',
            name='probabilidades_json',
            field=models.JSONField(help_text='Distribución de probabilidad'),
        ),
        migrations.CreateModel(
            name='Subida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fichero_personalizado', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subidas_relacionadas', to='analisis.analisis')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subidas',
                'ordering': ['-fecha_subida'],
                'unique_together': {('usuario', 'analisis')},
            },
        ),
    ]
