# Generated by Django 6.0.2 on 2026-02-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0005_remove_analisis_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='call_graph_json',
            field=models.JSONField(blank=True, help_text='Estructura de nodos y aristas', null=True),
        ),
    ]
