# Generated by Django 5.2.11 on 2026-02-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0006_analisis_call_graph_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetriaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_usage', models.FloatField()),
                ('gpu_usage', models.FloatField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
