# Generated by Django 5.2.11 on 2026-02-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0007_telemetriasistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logactividad',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
