# Generated by Django 5.2.11 on 2026-02-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0008_alter_logactividad_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricasModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=50)),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('support', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Métricas del Modelo',
            },
        ),
    ]
