# Generated by Django 5.2.11 on 2026-02-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0009_metricasmodelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefuncion',
            name='codigo_desensamblado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
