# Generated by Django 5.2.11 on 2026-04-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0010_detallefuncion_codigo_desensamblado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefuncion',
            name='complejidad_ciclomatica',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detallefuncion',
            name='features_vector',
            field=models.JSONField(blank=True, help_text='Valores numéricos de entrada pasados al modelo (input_dim)', null=True),
        ),
        migrations.AddField(
            model_name='detallefuncion',
            name='num_llamadas_sistema',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallefuncion',
            name='prediccion_especifica',
            field=models.JSONField(blank=True, help_text='Probabilidades individuales (softmax) de la función', null=True),
        ),
    ]
