# Generated by Django 5.2.11 on 2026-04-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0011_detallefuncion_complejidad_ciclomatica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='pseudo_label',
            field=models.BooleanField(default=True),
        ),
    ]
